[versions]
agp = "9.0.0"
commonsCompress = "1.28.0"
commonsValidator = "1.10.1"
flexbox = "3.0.0"
javaIniParser = "1.7"
kotlin = "2.3.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
mslinks = "1.0.6.2"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
swiperefreshlayout = "1.2.0"
activity = "1.12.2"
xz = "1.11"
androidtimer = "1.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
java-ini-parser = { module = "com.github.vincentrussell:java-ini-parser", version.ref = "javaIniParser" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
mslinks = { module = "com.github.vatbub:mslinks", version.ref = "mslinks" }
xz = { module = "org.tukaani:xz", version.ref = "xz" }
androidtimer = { module = "com.github.gustavlindberg99:androidtimer", version.ref = "androidtimer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
